#!/bin/bash

cd src
mkdir -p "${1}"/usr/{bin,share/cdm}
install -m755 cdm "${1}"/usr/bin/
install -m755 xlogout "${1}"/usr/bin/
install -m755 session-scraper "${1}"/usr/bin/
install -Dm644 cdmrc "${1}"/etc/cdmrc
install -m644 xinitrc* "${1}"/usr/share/cdm/
install -Dm755 zzz-cdm-profile.sh "${1}"/etc/profile.d/zzz-cdm-profile.sh
cp -Rf themes "${1}"/usr/share/cdm/
